name: Run saucedemo-webdriverio-tests in Docker container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: npm run docker:build

    - name: Run tests
      run: npm run docker:run

    - name: Generate Allure report
      run: docker run -it saucedemo-webdriverio-tests npm run allure:generate

    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
