name: Saucedemo-webdriverio-tests

on:
  push:
    branches:
      - main
      - fix-mistakes
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:all:chrome

    - name: Generate Allure report
      run: npm run allure:generate

    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES_TOKEN }}
        publish_dir: ./allure-report

  notify:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Post a comment with a link to the report
        uses: actions/github-script@v6
        with:
          script: |
            const reportUrl = `https://${{ github.repository_owner }}.github.io/${{ github.repository }}/`;

            // Додаткова перевірка на наявність github.context та payload
            if (github.context && github.context.payload) {
              if (github.context.payload.pull_request) {
                // Якщо є pull_request
                github.rest.issues.createComment({
                  issue_number: github.context.payload.pull_request.number,
                  owner: github.context.repo.owner,
                  repo: github.context.repo.repo,
                  body: `✅ Tests completed! View the report [here](${reportUrl})`
                });
              } else if (github.context.eventName === 'push') {
                // Якщо подія push
                const commitSha = github.context.sha;

                github.rest.repos.createCommitComment({
                  owner: github.context.repo.owner,
                  repo: github.context.repo.repo,
                  commit_sha: commitSha,
                  body: `✅ Tests completed! View the report [here](${reportUrl})`
                });
              } else {
                console.log('No suitable context for commenting.');
              }
            } else {
              console.log('Context or payload is undefined.');
            }
